-- Удаление таблиц в обратном порядке
DROP TABLE IF EXISTS UserVisits CASCADE;
DROP TABLE IF EXISTS UserActivityLog CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS task_status CASCADE;
DROP TABLE IF EXISTS referral CASCADE;
DROP TABLE IF EXISTS Users CASCADE;


